Profile/urls.py
from django.urls import path
from . import views

app_name = 'Profile'


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profiledetails/<int:id>/', views.profile_details, name='profile_details'),
    path('likes_button/', views.likes_button, name='likes_button'),
    path('faves/<int:id>/', views.faves, name='faves'),
    path('all_fav/', views.all_fav, name='all_fav'),
    path('comments/<int:id>/', views.comments, name='comments'),
    path('setcookie/', views.setcookie, name='setcookie'),
    path('getcookie/', views.getcookie, name='getcookie'),
    path('delcookie/', views.delcookie, name='delcookie'),
    path('setsession/', views.setsession, name='setsession'),
    path('getsession/', views.getsession, name='getsession'),
    path('delsession/', views.delsession, name='delssession'),
    path('login/', views.Login.as_view(), name='login'),
    path('sign/', views.sign, name='sign'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('Profile.urls', namespace='accounts')),
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    prof      = models.ForeignKey(User, on_delete=models.CASCADE)
    name      = models.CharField(max_length=100)
    title     = models.CharField(max_length=200)
    content   = models.TextField()
    slug      = models.SlugField(blank=True, null=True)
    likes     = models.ManyToManyField(User, related_name='likes',blank=True)
    fav       = models.ManyToManyField(User, related_name='fav', blank=True)


    def __str__(self):
        return self.name



class Comments(models.Model):
    profile = models.ForeignKey(Profile, related_name='comments', on_delete=models.CASCADE)
    name    = models.CharField(max_length=200)
    email   = models.EmailField()
    body    = models.TextField()



    def __str__(self):
        return self.name

Profile/forms.py
from django import forms
from .models import Comments
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'body']


class SignForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email' , 'first_name', 'last_name', 'password1', 'password2']

Profile/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from .models import Profile
from .forms import CommentForm, SignForm
from datetime import datetime, timedelta
from django.contrib.auth.views import LoginView
from django.contrib.auth import authenticate, login
# Create your views here.

def sign(request):
    if request.method == 'POST':
        forms = SignForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/accounts/profile')
    else:
        forms = SignForm()
    return render(request, 'profile/sign.html', {'forms':forms})




class Login(LoginView):
    template_name = 'registration/login.html'
    success_url = '/accounts/profile'


def setcookie(request):
    response = render(request, 'profile/setcookie.html')
    response.set_cookie('name','ahmed', expires=datetime.utcnow()+timedelta(days=10))
    return response

def getcookie(request):
    # name = request.COOKIES['name']
    name = request.COOKIES.get('name', 'Default Name....')
    return render(request, 'profile/getcookie.html', {'name':name})

def delcookie(request):
    response = render(request, 'profile/delcookie.html')
    response.delete_cookie('name')
    return response

def setsession(request):
    request.session['name'] = 'alaa'
    return render(request, 'profile/setsession.html')


def getsession(request):
    # name = request.session['name']
    name = request.session.get('name', default='ahmed')
    return render(request, 'profile/getsession.html', {'name':name})


def delsession(request):
    # if 'name' in request.session:
    #     del request.session['name']
    request.session.flush()
    return render(request, 'profile/delsession.html')




def comments(request, id):
    profile = get_object_or_404(Profile, id=id)
    btn = None
    if request.method == 'POST':
        forms = CommentForm(request.POST)
        if forms.is_valid():
            btn = forms.save(commit=False)
            btn.profile = profile
            btn.save()
            return HttpResponseRedirect('/accounts/profiledetails/' + str(profile.id))
    else:
        forms = CommentForm()
    return render(request, 'profile/page.html', {'forms':forms})



def profile(request):
    profiles = Profile.objects.all()
    context = {'profiles':profiles}
    return render(request, 'profile/home.html', context)


def profile_details(request, id):
    details = Profile.objects.get(id=id)
    is_liked = False
    if details.likes.filter(id=request.user.id).exists():
        is_liked = True

    is_fav = False
    if details.fav.filter(id=request.user.id).exists():
        is_fav = True

    comments = details.comments.all()
    lbl = None
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            lbl = form.save(commit=False)
            lbl.details = details
            lbl.save()
            form = CommentForm()
    else:
        form = CommentForm()
    context = {'details':details, 'is_liked':is_liked, 'is_fav':is_fav, 'comments':comments, 'form':form}
    return render(request, 'profile/profile_details.html', context)



def likes_button(request):
    profiles = get_object_or_404(Profile, id=request.POST.get('details_id'))
    is_liked = False
    if profiles.likes.filter(id=request.user.id).exists():
        profiles.likes.remove(request.user)
        is_liked = False
    else:
        profiles.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect('/accounts/profiledetails/'+ str(profiles.id))


def faves(request, id):
    profile = get_object_or_404(Profile, id=id)
    if profile.fav.filter(id=request.user.id).exists():
        profile.fav.remove(request.user)
    else:
        profile.fav.add(request.user)
    return HttpResponseRedirect('/accounts/profiledetails/' + str(profile.id))

def all_fav(request):
    favs = Profile.objects.filter(fav=request.user)
    context = {'favs':favs}
    return render(request, 'profile/fav.html', context)

Profile/templates/profile/delcookie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Del Cookie</title>
</head>
<body>
<h1>Del Cookies......................</h1>
</body>
</html>

Profile/templates/profile/delsession.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Del Session</title>
</head>
<body>
<h1>Del Session................</h1>
</body>
</html>

Profile/templates/profile/fav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>favorites</title>
</head>
<body>
<h1>Favourite</h1>
{% for fav in favs %}
<h1>{{fav}}</h1><br>
{% endfor %}
</body>
</html>

Profile/templates/profile/getcookie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GET Cookies</title>
</head>
<body>
<h1>Get Cookies</h1>
<h2>{{name}}</h2>
</body>
</html>

Profile/templates/profile/getsession.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get Session</title>
</head>
<body>
<h1>Get Session.....</h1>
<h2>{{name}}</h2>
</body>
</html>

Profile/templates/profile/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home profile</title>
</head>
<body>
<h1>Home Profile</h1>
{% for profile in profiles %}
{{profile.name}}<br>
{{profile.title}}<br>
{{profile.content}}<br>
<a href="{% url 'accounts:profile_details' profile.id %}">ProfileDetails</a>
<hr>
{% endfor %}
</body>
</html>

Profile/templates/profile/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comments</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit" value="Submit">
</form>
</body>
</html>

Profile/templates/profile/profile_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile Details</title>
</head>
<body>
<h1>Profile Details</h1>
<h1>{{details.name}}</h1>
<h1>{{details.title}}</h1>
<h1>{{details.content}}</h1>
<a href="{% url 'accounts:profile' %}">Home Profile</a>

<form method="post" action="{% url 'accounts:likes_button' %}">
    {% csrf_token %}
    {% if is_liked %}
    <button type="submit" name="details_id" value="{{details.id}}">DisLike</button>
    {% else %}
    <button type="submit" name="details_id" value="{{details.id}}">Like</button>
    {% endif %}
</form>



<form method="post" action="{% url 'accounts:faves' details.id %}">
    {% csrf_token %}
    {% if is_fav %}
    <button type="submit" name="details_id" value="{{details.id}}">DisFavourite</button>
    {% else %}
    <button type="submit" name="details_id" value="{{details.id}}">Favourite</button>
    {% endif %}
</form>
<br>
<a href="{% url 'accounts:comments' details.id %}">Add Comment</a>

<h1>Comments ......</h1>
{% if not comments %}
No Comment.....

{% else %}
{% for comment in comments  %}
{{comment.name}}<br>
{{comment.email}}<br>
{{comment.body}}<br>
{% endfor %}
{% endif %}

<br>


<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit"/>
</form>








</body>
</html>

Profile/templates/profile/setcookie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Set Cookie</title>
</head>
<body>
<h1>Set Cookie........</h1>
</body>
</html>

Profile/templates/profile/setsession.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Set Session</title>
</head>
<body>
<h1>set session.........</h1>
</body>
</html>

Profile/templates/profile/sign.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>
<h1>Registration</h1>
<form method="post">
    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit" value="Sign"/>
</form>
</body>
</html>